// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'TheNavBar': typeof import("../components/TheNavBar.vue")['default'],
    'Hive': typeof import("../components/hive.vue")['default'],
    'Location': typeof import("../components/location.vue")['default'],
    'NewLocation': typeof import("../components/newLocation.vue")['default'],
    'TheHeader': typeof import("../components/theHeader.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyTheNavBar': typeof import("../components/TheNavBar.vue")['default'],
    'LazyHive': typeof import("../components/hive.vue")['default'],
    'LazyLocation': typeof import("../components/location.vue")['default'],
    'LazyNewLocation': typeof import("../components/newLocation.vue")['default'],
    'LazyTheHeader': typeof import("../components/theHeader.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const TheNavBar: typeof import("../components/TheNavBar.vue")['default']
export const Hive: typeof import("../components/hive.vue")['default']
export const Location: typeof import("../components/location.vue")['default']
export const NewLocation: typeof import("../components/newLocation.vue")['default']
export const TheHeader: typeof import("../components/theHeader.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyTheNavBar: typeof import("../components/TheNavBar.vue")['default']
export const LazyHive: typeof import("../components/hive.vue")['default']
export const LazyLocation: typeof import("../components/location.vue")['default']
export const LazyNewLocation: typeof import("../components/newLocation.vue")['default']
export const LazyTheHeader: typeof import("../components/theHeader.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
